openapi: 3.0.2
info:
  title: Creative Automobile Reporting Service
  version: "1.0.0"
  description: "Provides fictional information about cars"
  license:
    name: "ISC"
    url: "https://github.com/app-factory-team/api-creation-demo/blob/master/licence.md"
  contact:
    name: App Factory Team
    url: https://github.com/app-factory-team/api-creation-demo/issues
  server:
    url: http://localhost:3000/
    description: Local development environment
externalDocs:
  url: https://github.com/app-factory-team/api-creation-demo/wiki
paths:
  /cars:
    get:
      description: Returns information about cars based on provided registrations
      responses:
        "200":
          description: A list of cars
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items: "#components/schema/car"
components:
